# Generated by Django 5.2.9 on 2026-01-10 22:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("comment", "Comentário"),
                            ("follow", "Novo seguidor"),
                            ("favorite", "Favorito"),
                            ("upload_approved", "Upload aprovado"),
                            ("audio_approved", "Áudio aprovado"),
                        ],
                        default="comment",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("message", models.TextField(max_length=500, verbose_name="Mensagem")),
                (
                    "link",
                    models.CharField(
                        blank=True, help_text="URL para onde a notificação leva", max_length=500, verbose_name="Link"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lida")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinatário",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Remetente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["recipient", "-created_at"], name="users_notif_recipie_458498_idx"),
                    models.Index(fields=["is_read"], name="users_notif_is_read_316047_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserFollow",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                (
                    "followed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Seguido",
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Seguidor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seguir Usuário",
                "verbose_name_plural": "Seguir Usuários",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["follower", "-created_at"], name="users_userf_followe_b6d69c_idx"),
                    models.Index(fields=["followed", "-created_at"], name="users_userf_followe_122d15_idx"),
                ],
                "unique_together": {("follower", "followed")},
            },
        ),
    ]
