# Generated by Django 5.2.9 on 2026-01-06 20:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HymnBook",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Nome do hinário", max_length=255, unique=True, verbose_name="Nome"
                    ),
                ),
                (
                    "intro_name",
                    models.CharField(
                        blank=True, help_text="Nome de exibição curto", max_length=100, verbose_name="Nome curto"
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="Slug")),
                (
                    "owner_name",
                    models.CharField(
                        help_text="Pessoa que recebeu o hinário (texto livre)",
                        max_length=255,
                        verbose_name="Nome do dono",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="hymn_covers/", verbose_name="Imagem de capa"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuário cadastrado como dono deste hinário",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_hymnbooks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário dono",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hinário",
                "verbose_name_plural": "Hinários",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Hymn",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Número sequencial do hino no hinário", verbose_name="Número"
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255, verbose_name="Título")),
                ("text", models.TextField(help_text="Letra completa do hino", verbose_name="Letra")),
                (
                    "received_at",
                    models.DateField(
                        blank=True, help_text="Data em que o hino foi recebido", null=True, verbose_name="Recebido em"
                    ),
                ),
                (
                    "offered_to",
                    models.CharField(
                        blank=True, help_text="Pessoa dedicatária", max_length=255, verbose_name="Oferecido para"
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        blank=True, help_text="Ex: Valsa, Marcha, Mazurca", max_length=50, verbose_name="Estilo musical"
                    ),
                ),
                (
                    "extra_instructions",
                    models.TextField(
                        blank=True, help_text="Instruções especiais de canto", verbose_name="Instruções extras"
                    ),
                ),
                (
                    "repetitions",
                    models.CharField(
                        blank=True,
                        help_text="Ex: 1-4, 5-8 (indicação de estrofes a repetir)",
                        max_length=100,
                        verbose_name="Repetições",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "hymn_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hymns",
                        to="hymns.hymnbook",
                        verbose_name="Hinário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hino",
                "verbose_name_plural": "Hinos",
                "ordering": ["hymn_book", "number"],
            },
        ),
        migrations.AddIndex(
            model_name="hymnbook",
            index=models.Index(fields=["name"], name="hymns_hymnb_name_e48b0a_idx"),
        ),
        migrations.AddIndex(
            model_name="hymnbook",
            index=models.Index(fields=["owner_name"], name="hymns_hymnb_owner_n_3d2789_idx"),
        ),
        migrations.AddIndex(
            model_name="hymnbook",
            index=models.Index(fields=["created_at"], name="hymns_hymnb_created_5adb7e_idx"),
        ),
        migrations.AddIndex(
            model_name="hymn",
            index=models.Index(fields=["hymn_book", "number"], name="hymns_hymn_hymn_bo_431c81_idx"),
        ),
        migrations.AddIndex(
            model_name="hymn",
            index=models.Index(fields=["title"], name="hymns_hymn_title_99a253_idx"),
        ),
        migrations.AddIndex(
            model_name="hymn",
            index=models.Index(fields=["received_at"], name="hymns_hymn_receive_c4b85a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="hymn",
            unique_together={("hymn_book", "number")},
        ),
    ]
