# Generated by Django 5.2.9 on 2026-01-10 15:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hymns", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HymnBookVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "version_name",
                    models.CharField(
                        help_text="Ex: Edição 2010, Versão revisada", max_length=100, verbose_name="Nome da versão"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Diferenças desta versão", verbose_name="Descrição"),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="hymnbooks/pdfs/", verbose_name="Arquivo PDF"),
                ),
                (
                    "yaml_file",
                    models.FileField(blank=True, null=True, upload_to="hymnbooks/yaml/", verbose_name="Arquivo YAML"),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Versão principal exibida", verbose_name="Versão primária"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "hymn_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="hymns.hymnbook",
                        verbose_name="Hinário",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_versions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enviado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versão de Hinário",
                "verbose_name_plural": "Versões de Hinários",
                "ordering": ["-is_primary", "-created_at"],
                "indexes": [
                    models.Index(fields=["hymn_book", "is_primary"], name="hymns_hymnb_hymn_bo_5d93b9_idx"),
                    models.Index(fields=["uploaded_by"], name="hymns_hymnb_uploade_0726ba_idx"),
                    models.Index(fields=["created_at"], name="hymns_hymnb_created_9c50c8_idx"),
                ],
            },
        ),
    ]
