# Generated by Django 5.2.9 on 2026-01-10 22:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hymns", "0002_hymnbookversion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("text", models.TextField(max_length=1000, verbose_name="Comentário")),
                (
                    "is_approved",
                    models.BooleanField(default=True, help_text="Pode ser moderado", verbose_name="Aprovado"),
                ),
                (
                    "is_flagged",
                    models.BooleanField(default=False, help_text="Reportado por abuso", verbose_name="Reportado"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "hymn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="hymns.hymn",
                        verbose_name="Hino",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentário",
                "verbose_name_plural": "Comentários",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["hymn", "-created_at"], name="hymns_comme_hymn_id_b95d36_idx"),
                    models.Index(fields=["user", "-created_at"], name="hymns_comme_user_id_bbbdac_idx"),
                    models.Index(fields=["is_approved"], name="hymns_comme_is_appr_089336_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                (
                    "hymn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="hymns.hymn",
                        verbose_name="Hino",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorito",
                "verbose_name_plural": "Favoritos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="hymns_favor_user_id_2a139d_idx"),
                    models.Index(fields=["hymn"], name="hymns_favor_hymn_id_0e2e8b_idx"),
                ],
                "unique_together": {("user", "hymn")},
            },
        ),
        migrations.CreateModel(
            name="HymnAudio",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "audio_file",
                    models.FileField(
                        help_text="MP3, OGG ou FLAC. Máximo 25MB.",
                        upload_to="hymns/audio/%Y/%m/",
                        verbose_name="Arquivo de áudio",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Gravação Studio 2023",
                        max_length=200,
                        verbose_name="Título da gravação",
                    ),
                ),
                (
                    "source",
                    models.CharField(blank=True, help_text="Onde foi gravado", max_length=255, verbose_name="Fonte"),
                ),
                (
                    "recorded_at",
                    models.DateField(
                        blank=True, help_text="Quando foi gravado", null=True, verbose_name="Data de gravação"
                    ),
                ),
                (
                    "credits",
                    models.TextField(
                        blank=True, help_text="Quem cantou, gravou, produziu, etc.", verbose_name="Créditos"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True, help_text="Duração em segundos", null=True, verbose_name="Duração (segundos)"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="Tamanho do arquivo em bytes", null=True, verbose_name="Tamanho (bytes)"
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        blank=True, help_text="MP3, OGG, FLAC, etc.", max_length=10, verbose_name="Formato"
                    ),
                ),
                ("is_approved", models.BooleanField(default=False, help_text="Moderação", verbose_name="Aprovado")),
                (
                    "allow_download",
                    models.BooleanField(
                        default=True, help_text="Usuários podem baixar o arquivo", verbose_name="Permitir download"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "hymn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audios",
                        to="hymns.hymn",
                        verbose_name="Hino",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_audios",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enviado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Áudio de Hino",
                "verbose_name_plural": "Áudios de Hinos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["hymn", "-created_at"], name="hymns_hymna_hymn_id_ce40a3_idx"),
                    models.Index(fields=["is_approved"], name="hymns_hymna_is_appr_b2dc3c_idx"),
                    models.Index(fields=["uploaded_by"], name="hymns_hymna_uploade_030d70_idx"),
                ],
            },
        ),
    ]
